import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Policy Pilot',
  description: 'Terms of Service for Policy Pilot. Read the terms governing your use of our insurance grading platform.',
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-100 text-slate-900">
      {/* Top navigation */}
      <nav className="bg-slate-900 pt-4 sm:pt-4">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          <div className="flex items-center gap-3">
            <img src="/logo.png" alt="PolicyPilot" className="h-9 w-9 rounded-xl" />
            <span className="text-lg font-semibold tracking-tight text-white">PolicyPilot</span>
          </div>
          <div className="hidden items-center gap-8 text-[15px] font-semibold text-slate-100 md:flex">
            <Link href="/#how" className="transition-colors hover:text-white">
              How it works
            </Link>
            <Link href="/#score" className="transition-colors hover:text-white">
              The score
            </Link>
            <Link href="/#security" className="transition-colors hover:text-white">
              Security
            </Link>
            <Link href="/#faq" className="transition-colors hover:text-white">
              FAQ
            </Link>
          </div>
          <Link
            href="/get-policy"
            className="inline-flex items-center justify-center rounded-full bg-gradient-to-r from-blue-600 to-cyan-500 px-5 py-2 text-sm font-semibold text-white shadow-lg shadow-blue-600/25 transition-all duration-200 hover:-translate-y-0.5"
          >
            Get My Free Score
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-3xl font-bold text-slate-900">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">
          Last updated: February 16, 2026
        </p>

        <div className="mt-10 space-y-10 text-[15px] leading-relaxed text-slate-700">
          {/* Intro */}
          <section>
            <p>
              These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the website{' '}
              <a href="https://www.mypolicypilot.ai" className="text-blue-600 hover:underline">
                www.mypolicypilot.ai
              </a>{' '}
              and the services provided by Policy Pilot LLC (&ldquo;Policy Pilot,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). By using our Service, you agree to these Terms. If you do not agree, please do not use the Service.
            </p>
          </section>

          {/* 1 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">1. Description of Service</h2>
            <p className="mt-2">
              Policy Pilot is a free, AI-powered insurance policy analysis tool. You connect your existing insurance policies through a secure third-party integration, and we generate a report grading your coverage based on industry standards. The report includes scores, coverage gap analysis, and general recommendations.
            </p>
          </section>

          {/* 2 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">2. Not Insurance Advice</h2>
            <p className="mt-2">
              <strong>
                The Service is for informational and educational purposes only. It does not constitute insurance advice, financial advice, or a recommendation to purchase, cancel, or modify any insurance policy.
              </strong>
            </p>
            <p className="mt-2">
              Policy Pilot is not an insurance company, insurance broker, or licensed insurance agent. Our reports are generated by artificial intelligence and are based on general industry standards — they do not account for your specific financial situation, risk profile, state regulations, or individual needs.
            </p>
            <p className="mt-2">
              You should always consult with a licensed insurance professional before making changes to your coverage.
            </p>
          </section>

          {/* 3 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">3. Eligibility</h2>
            <p className="mt-2">
              You must be at least 18 years old to use the Service. By using the Service, you represent that you are at least 18 years of age and have the legal capacity to enter into these Terms.
            </p>
          </section>

          {/* 4 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">4. Your Use of the Service</h2>
            <p className="mt-2">You agree to:</p>
            <ul className="mt-2 list-disc space-y-1 pl-6">
              <li>Provide accurate information when using the Service.</li>
              <li>Use the Service only for lawful, personal, non-commercial purposes.</li>
              <li>Not attempt to reverse-engineer, scrape, or interfere with the Service.</li>
              <li>Not use the Service to generate reports for policies you do not own or are not authorized to access.</li>
            </ul>
          </section>

          {/* 5 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">5. Third-Party Services</h2>
            <p className="mt-2">
              Our Service relies on third-party providers, including Canopy Connect for policy data retrieval, OpenAI for AI-powered analysis, and others described in our{' '}
              <Link href="/privacy" className="text-blue-600 hover:underline">
                Privacy Policy
              </Link>
              . These providers have their own terms and privacy policies. We are not responsible for the availability, accuracy, or practices of third-party services.
            </p>
            <p className="mt-2">
              When you connect your insurance account through Canopy Connect, you are subject to Canopy Connect&rsquo;s terms of service. Your carrier login credentials are handled entirely by Canopy Connect and are never transmitted to or stored by Policy Pilot.
            </p>
          </section>

          {/* 6 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">6. Accuracy and Limitations</h2>
            <p className="mt-2">
              Reports are generated by artificial intelligence and are based on the policy data retrieved at the time of analysis. While we strive for accuracy, we do not guarantee that reports are complete, error-free, or up to date. Policy data may be incomplete depending on what your carrier provides.
            </p>
            <p className="mt-2">
              Scores, grades, and recommendations are general assessments and should not be the sole basis for insurance decisions.
            </p>
          </section>

          {/* 7 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">7. Intellectual Property</h2>
            <p className="mt-2">
              All content, features, branding, and technology of the Service — including but not limited to text, graphics, logos, scoring methodology, and report formats — are owned by Policy Pilot LLC and are protected by applicable intellectual property laws.
            </p>
            <p className="mt-2">
              You may download and share your own report for personal use. You may not reproduce, distribute, or commercially exploit any part of the Service without our prior written consent.
            </p>
          </section>

          {/* 8 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">8. Disclaimer of Warranties</h2>
            <p className="mt-2">
              THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
            <p className="mt-2">
              We do not warrant that the Service will be uninterrupted, secure, or error-free, or that the results obtained from the Service will be accurate or reliable.
            </p>
          </section>

          {/* 9 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">9. Limitation of Liability</h2>
            <p className="mt-2">
              TO THE FULLEST EXTENT PERMITTED BY LAW, POLICY PILOT LLC AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM OR RELATED TO YOUR USE OF THE SERVICE, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, DATA, OR OTHER INTANGIBLE LOSSES.
            </p>
            <p className="mt-2">
              OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING FROM OR RELATED TO THE SERVICE SHALL NOT EXCEED ONE HUNDRED DOLLARS ($100).
            </p>
          </section>

          {/* 10 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">10. Indemnification</h2>
            <p className="mt-2">
              You agree to indemnify and hold harmless Policy Pilot LLC from any claims, damages, losses, or expenses (including reasonable attorney&rsquo;s fees) arising out of your use of the Service, your violation of these Terms, or your violation of any third-party rights.
            </p>
          </section>

          {/* 11 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">11. Termination</h2>
            <p className="mt-2">
              We reserve the right to suspend or terminate your access to the Service at any time, for any reason, without notice. Upon termination, your right to use the Service ceases immediately.
            </p>
          </section>

          {/* 12 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">12. Governing Law</h2>
            <p className="mt-2">
              These Terms shall be governed by and construed in accordance with the laws of the State of Arizona, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved in the state or federal courts located in Maricopa County, Arizona.
            </p>
          </section>

          {/* 13 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">13. Changes to These Terms</h2>
            <p className="mt-2">
              We may update these Terms from time to time. We will notify you of material changes by posting the updated Terms on this page with a revised &ldquo;Last updated&rdquo; date. Your continued use of the Service after any changes constitutes your acceptance of the updated Terms.
            </p>
          </section>

          {/* 14 */}
          <section>
            <h2 className="text-xl font-semibold text-slate-900">14. Contact Us</h2>
            <p className="mt-2">
              If you have any questions about these Terms, please contact us at:
            </p>
            <p className="mt-3 font-medium text-slate-900">
              Policy Pilot LLC
              <br />
              <a href="mailto:admin@mypolicypilot.ai" className="text-blue-600 hover:underline">
                admin@mypolicypilot.ai
              </a>
            </p>
          </section>
        </div>
      </main>

      {/* Final CTA + Footer */}
      <section className="relative overflow-hidden bg-slate-900 pt-20 pb-12">
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute -left-32 top-16 h-[280px] w-[280px] rounded-full bg-blue-600/30 blur-[120px]" />
          <div className="absolute right-0 top-0 h-[360px] w-[360px] rounded-full bg-cyan-500/20 blur-[140px]" />
        </div>
        <div className="relative mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8">
          <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-semibold uppercase tracking-[0.2em] text-slate-200">
            Free analysis in 2 minutes
          </div>
          <h2 className="mt-6 text-3xl font-semibold text-white sm:text-4xl lg:text-5xl">
            Get clarity on your insurance — instantly.
          </h2>
          <p className="mt-3 text-lg text-slate-300">
            Join thousands of homeowners and renters using PolicyPilot to uncover coverage gaps and savings.
          </p>
          <div className="mt-10">
            <Link
              href="/get-policy"
              className="inline-flex items-center justify-center rounded-full bg-white px-8 py-3 text-base font-semibold text-slate-900 shadow-lg transition-all duration-200 hover:-translate-y-0.5"
            >
              Get My Free Score
            </Link>
          </div>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-4 text-sm text-slate-300">
            <span>Completely free</span>
            <span className="hidden h-1 w-1 rounded-full bg-slate-400 sm:inline-block" />
            <span>No credit card</span>
            <span className="hidden h-1 w-1 rounded-full bg-slate-400 sm:inline-block" />
            <span>Private & secure</span>
          </div>
        </div>

        {/* Footer */}
        <div className="relative mt-20">
          <div className="mx-auto max-w-7xl px-4 pt-10 sm:px-6 lg:px-8">
            <div className="flex flex-col items-center gap-6 sm:grid sm:grid-cols-3 sm:items-center">
              <div className="flex items-center gap-3">
                <img src="/logo.png" alt="PolicyPilot" className="h-9 w-9 rounded-xl" />
                <span className="text-sm font-semibold text-white">PolicyPilot</span>
              </div>
              <div className="flex flex-wrap items-center justify-center gap-6 text-sm text-slate-400">
                <Link href="/privacy" className="transition-colors hover:text-white">
                  Privacy Policy
                </Link>
                <Link href="/terms" className="transition-colors hover:text-white">
                  Terms
                </Link>
                <Link href="/contact" className="transition-colors hover:text-white">
                  Contact
                </Link>
              </div>
              {/* <div className="flex items-center justify-end gap-3 text-slate-500">
                {['X', 'LinkedIn', 'Facebook'].map((social) => (
                  <a key={social} href="#" className="text-xs font-semibold uppercase tracking-[0.2em] transition-colors hover:text-white">
                    {social}
                  </a>
                ))}
              </div> */}
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
